spin_version = "1"
authors = ["{{authors}}"]
description = "{{project-description}}"
name = "{{project-name}}"
trigger = { type = "http", base = "{{http-base}}" }
version = "0.1.0"

[[component]]
id = "{{project-name | kebab_case}}"
source = "target/spin-http-js.wasm"
[component.trigger]
route = "{{http-path}}"
[component.build]
command = "npm run build"
