spin_manifest_version = 2

[application]
authors = ["karthik2804 <karthik.ganeshram@fermyon.com>"]
description = ""
name = "spin-postgres"
version = "0.1.0"

[[trigger.http]]
route = "/..."
component = "spin-postgres"

[component.spin-postgres]
source = "target/spin-postgres.wasm"
exclude_files = ["**/node_modules"]
allowed_outbound_hosts = ["postgres://*:*"]
[component.spin-postgres.build]
command = "npm run build"
watch = ["src/**/*.ts", "package.json"]
