[package]
name = "spin-js-cli"
version = "0.6.0"
edition = "2021"

[[bin]]
name = "spinjs"
path = "src/main.rs"

[dependencies]
anyhow = "1.0"
binaryen = { git = "https://github.com/pepyakin/binaryen-rs" }
clap = { version = "4.1.4", features = [ "derive" ] }
tempfile = "3.2.0"
wizer = "3.0.0"
