spin_manifest_version = 2

[application]
authors = ["karthik2804 <karthik.ganeshram@fermyon.com>"]
description = ""
name = "outbound-http"
version = "0.1.0"

[[trigger.http]]
route = "/..."
component = "outbound-http"

[component.outbound-http]
source = "target/outbound-http.wasm"
exclude_files = ["**/node_modules"]
[component.outbound-http.build]
command = "npm run build"
watch = ["src/**/*.ts", "package.json"]
