spin_manifest_version = 2

[application]
authors = ["{{authors}}"]
description = "{{project-description}}"
name = "{{project-name}}"
version = "0.1.0"

[[trigger.http]]
route = "{{http-path}}"
component = "{{project-name | kebab_case}}"

[component.{{project-name | kebab_case}}]
source = "target/{{project-name | kebab_case}}.wasm"
exclude_files = ["**/node_modules"]
[component.{{project-name | kebab_case}}.build]
{% if enable-experimental == "y" or enable-experimental == "Y" %}
command = "npm run build --experimental"
{% else %}
command = "npm run build"
{% endif %}
watch = ["src/**/*.ts", "package.json"]