name: Test

on:
  push:
    branches: [ feat/sdk-v2 ]
  pull_request:
    branches: [ feat/sdk-v2 ]
  workflow_dispatch:

jobs:
  lint_and_test:
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v3

        - name: Use Node.js 20
          uses: actions/setup-node@v3
          with:
            node-version: 20

        - name: Install depencies
          shell: bash
          run: npm install

        - name: Run prettier check
          shell: bash
          run: npm run fmt-check

        - name: Install spin
          uses: engineerd/configurator@v0.0.8
          with:
            name: "spin"
            url: "https://github.com/fermyon/spin/releases/download/v2.5.0/spin-v2.5.0-linux-amd64.tar.gz"
            pathInArchive: "spin"

        - name: Run Test
          shell: bash
          run: |
            cd test
            ./test.sh